name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DeployToken }}
          external_repository: hzmangel/hzmangel.github.io
          publish_dir: ./public
          user_name: hzmangel
          user_email: hzmangel@gmail.com
          publish_branch: master
          #cname: blog.hzmangel.info
